/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Words', [{
      word: 'weather',
      translation: 'погода',
      theme_id: 1,
      created_by: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'snow',
      translation: 'снег',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sun',
      translation: 'солнце',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cold',
      translation: 'холодно',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'hot',
      translation: 'жарко',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'warm',
      translation: 'тепло',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'rain',
      translation: 'дождь',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'wind',
      translation: 'ветер',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'winter',
      translation: 'зима',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'summer',
      translation: 'лето',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'mist',
      translation: 'туман',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'spring',
      translation: 'весна',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'storm',
      translation: 'буря',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'autumn',
      translation: 'осень',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'ice',
      translation: 'лёд',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'parents',
      translation: 'родители',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'father',
      translation: 'отец',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'mother',
      translation: 'мать',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'daughter',
      translation: 'дочь',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'brother',
      translation: 'брат',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'twins',
      translation: 'близнецы',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'grandfather',
      translation: 'дедушка',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'grandmother',
      translation: 'бабушка',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'husband',
      translation: 'муж',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'child',
      translation: 'ребенок',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sister',
      translation: 'сестра',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'uncle',
      translation: 'дядя',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'aunt',
      translation: 'тетя',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'relative',
      translation: 'родственник',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'nephew',
      translation: 'племянник',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'food',
      translation: 'еда',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'coffee',
      translation: 'кофе',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cheese',
      translation: 'сыр',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'salad',
      translation: 'салат',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'soup',
      translation: 'суп',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'meat',
      translation: 'мясо',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fish',
      translation: 'рыба',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'bread',
      translation: 'хлеб',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'juice',
      translation: 'сок',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fruit',
      translation: 'фрукты',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'tea',
      translation: 'чай',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'pepper',
      translation: 'перец',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sausages',
      translation: 'сосиски',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'potatoe',
      translation: 'картофель',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'chicken',
      translation: ' курица',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'clothes',
      translation: 'одежда',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'jeans',
      translation: 'джинсы',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'dress',
      translation: 'платье',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'jacket',
      translation: 'куртка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'skirt',
      translation: 'юбка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sweater',
      translation: 'свитер',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'boots',
      translation: 'ботинки',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cap',
      translation: 'шапка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'scarf',
      translation: 'шарф',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'coat',
      translation: 'пальто',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'blouse',
      translation: 'блузка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'belt',
      translation: 'ремень',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sock',
      translation: 'носок',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'underpants',
      translation: 'трусы',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'profession',
      translation: 'профессия',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'programmer',
      translation: 'программист',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'designer',
      translation: 'дизайнер',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'actort',
      translation: 'актер',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'teacher',
      translation: 'учитель',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'policeman',
      translation: 'полицейский',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fireman',
      translation: 'пожарный',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'scientist',
      translation: 'ученый',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'postman',
      translation: 'почтальон',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'librarian',
      translation: 'библиотекарь',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'nurse',
      translation: 'медсестра',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'singer',
      translation: 'певец',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'lawyer',
      translation: 'юрист',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'secretary',
      translation: 'секретарь',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'bodyguard',
      translation: 'телохранитель',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'appearance',
      translation: 'внешность',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'height',
      translation: 'рост',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'hair',
      translation: 'волосы',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'eyes',
      translation: 'глаза',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'teeth',
      translation: 'зубы',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'arms',
      translation: 'руки',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'legs',
      translation: 'ноги',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'slim',
      translation: 'стройный',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'athletic',
      translation: 'спортивный',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'tall',
      translation: 'высокий',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fat',
      translation: 'толстый',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'handsome',
      translation: 'красивый',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'грязный',
      translation: 'dirty',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'bald',
      translation: 'лысый',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'scar',
      translation: 'шрам',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'shark',
      translation: 'акула',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'ram',
      translation: 'баран',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'squirrel',
      translation: 'белка',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'wolf',
      translation: 'волк',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'bear',
      translation: 'медведь',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fox',
      translation: 'лиса',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cow',
      translation: 'корова',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'donkey',
      translation: 'осел',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'pig',
      translation: 'свинья',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'dog',
      translation: 'собака',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cat',
      translation: 'кошка',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'beaver',
      translation: 'бобр',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'raccon',
      translation: 'енот',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'lizard',
      translation: 'ящер',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'lamb',
      translation: 'ягненок',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'monkey',
      translation: 'обезьяна',
      theme_id: 7,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'arm',
      translation: 'рука',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'bone',
      translation: 'кость',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'leg',
      translation: 'нога',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'eye',
      translation: 'глаз',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'neck',
      translation: 'шея',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'body',
      translation: 'тело',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'brain',
      translation: 'мозг',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'chin',
      translation: 'подбородок',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'ear',
      translation: 'ухо',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'gum',
      translation: 'десна',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'head',
      translation: 'голова',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'lip',
      translation: 'губа',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'nail',
      translation: 'ноготь',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'nose',
      translation: 'нос',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'shoulder',
      translation: 'плечо',
      theme_id: 8,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'beige',
      translation: 'бежевый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'white',
      translation: 'белый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'turquoise',
      translation: 'бирюзовый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'pale',
      translation: 'бледный',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'yellow',
      translation: 'желтый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'green',
      translation: 'зеленый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'gold',
      translation: 'золотой',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'firebrick',
      translation: 'кирпичный',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'red',
      translation: 'красный',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'copper',
      translation: 'медный',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'orange',
      translation: 'оранжевый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'ash',
      translation: 'пепельный',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'blue',
      translation: 'синий',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'grey',
      translation: 'серый',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'dark',
      translation: 'темный',
      theme_id: 9,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
