/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Words', [{
      word: 'weather',
      translation: 'погода',
      theme_id: 1,
      created_by: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'snow',
      translation: 'снег',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sun',
      translation: 'солнце',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cold',
      translation: 'холодно',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'hot',
      translation: 'жарко',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'warm',
      translation: 'тепло',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'rain',
      translation: 'дождь',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'wind',
      translation: 'ветер',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'winter',
      translation: 'зима',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cloud',
      translation: 'облако',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'summer',
      translation: 'лето',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'mist',
      translation: 'туман',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'spring',
      translation: 'весна',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'storm',
      translation: 'буря',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'autumn',
      translation: 'осень',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'ice',
      translation: 'лёд',
      theme_id: 1,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'parents',
      translation: 'родители',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'father',
      translation: 'отец',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'mother',
      translation: 'мать',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'daughter',
      translation: 'дочь',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'brother',
      translation: 'брат',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'twins',
      translation: 'близнецы',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'grandfather',
      translation: 'дедушка',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'grandmother',
      translation: 'бабушка',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'husband',
      translation: 'муж',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'child',
      translation: 'ребенок',
      theme_id: 2,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'food',
      translation: 'еда',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'coffee',
      translation: 'кофе',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cheese',
      translation: 'сыр',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'salad',
      translation: 'салат',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'soup',
      translation: 'суп',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'meat',
      translation: 'мясо',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fish',
      translation: 'рыба',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'bread',
      translation: 'хлеб',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'juice',
      translation: 'сок',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'fruit',
      translation: 'фрукты',
      theme_id: 3,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'clothes',
      translation: 'одежда',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'jeans',
      translation: 'джинсы',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'dress',
      translation: 'платье',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'jacket',
      translation: 'куртка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'skirt',
      translation: 'юбка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'sweater',
      translation: 'свитер',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'boots',
      translation: 'ботинки',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'cap',
      translation: 'шапка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'scarf',
      translation: 'шарф',
      theme_id: 4,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'profession',
      translation: 'профессия',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a programmer',
      translation: 'программист',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a designer',
      translation: 'дизайнер',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'an actort',
      translation: 'актер',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a teacher',
      translation: 'учитель',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a policeman',
      translation: 'полицейский',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a fireman',
      translation: 'пожарный',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a scientist',
      translation: 'ученый',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a postman',
      translation: 'почтальон',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'a librarian',
      translation: 'библиотекарь',
      theme_id: 5,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'appearance',
      translation: 'внешность',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'height',
      translation: 'рост',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'hair',
      translation: 'волосы',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'eyes',
      translation: 'глаза',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'teeth',
      translation: 'зубы',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'arms',
      translation: 'руки',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'legs',
      translation: 'ноги',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'slim',
      translation: 'стройный',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'athletic',
      translation: 'спортивный',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      word: 'tall',
      translation: 'высокий',
      theme_id: 6,
      created_by: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  },
};
